version: '3.8'
services:
  app:
    # Build the image using the Dockerfile in the current directory
    build: .
    # Map port 3000 on your machine to port 80 in the container
    ports:
      - "3000:80"
    # Restart the container automatically if it crashes
    restart: always
    # Set the container name for easy identification
    container_name: online-virtual-workplace